name: Run Script | Case Install

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make the script `run.sh` executable
      run: chmod +x `/setup/setup_compression_status.sh`

    - name: Run script `run.sh` and wait for user input
      run: |
        python3 ./setup/setup_compression_status.sh no