name: Compression Status | Case No

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make the script `setup_campression.py` executable
      run: sudo chmod +x `./setup/setup_compression_status.py`

    - name: Run script `setup_compression.py` and wait for user input
      run: |
       ./setup/setup_compression_status.py no