name: Hotfix Test

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make the scripts executable
      run: |
       sudo chmod +x ./hotfix.py
       sudo chmod +x ./setup/setup_nix.py
       sudo chmod +x ./setup/setup_qemu.py
       sudo chmod +x ./setup/flake_qemu.nix

    - name: Run script `hotfix.py`
      run: |
       python3 ./hotfix.py
       python3 ./setup/setup_nix.py
       python3 ./setup/setup_qemu.py