name: Run Script | Case Install

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make  the script `run.sh` executable
      run: chmod +x run.sh

    - name: Run script `run.sh`
      run: sudo ./run.sh

    - name: Type 'install' to check the install scenario
      run: echo "install"