name: Run Script Test | Case Install

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make the script `hotfix.sh` executable
      run: sudo chmod +x hotfix.sh

    - name: Run script `hotfix.sh` and wait for user input
      run: |
        sudo ./hotfix.sh install